#!/usr/bin/bash

#SBATCH --mail-type=END
#SBATCH --mail-user=sonas@ccf.org
#SBATCH --job-name=preprocess_bam
#SBATCH -n 20
#SBATCH --mem-per-cpu=3900

#SBATCH -o prep_GTFdb_%J.out
#SBATCH -e prep_GTFdb_%J.err

export LD_LIBRARY_PATH=/cm/local/apps/gcc/8.2.0/lib64/
module load gcc/8.2.0
module load samtools/1.9
module load subset-bam/1.1.0
module load python/3.8.6 #To use umi_tools

WORKING_DIR='/home/sonas/beegfs/tools/polyAfilter/'
GTF="/home/sonas/beegfs/ref/refdata-gex-GRCh38-2020-A/genes/genes.gtf"

filter_dir='/home/sonas/beegfs/APA/scPASU/output/1_process_bam/1d_filtered_bam/'

DB=${filter_dir}"gtfdb.db"
NTHREADS=20

#SCRIPT
cd $WORKING_DIR

# Create the GTF database
python polyAfilter.py createDB -v $GTF $DB

